// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	models "GoMail/app/repository/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CleanupExpiredTokens provides a mock function with given fields: ctx, beforeTime
func (_m *Repository) CleanupExpiredTokens(ctx context.Context, beforeTime time.Time) (int64, error) {
	ret := _m.Called(ctx, beforeTime)

	if len(ret) == 0 {
		panic("no return value specified for CleanupExpiredTokens")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, beforeTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, beforeTime)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, beforeTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEmail provides a mock function with given fields: ctx, id
func (_m *Repository) DeleteEmail(ctx context.Context, id interface{}) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindEmailLogByID provides a mock function with given fields: ctx, id
func (_m *Repository) FindEmailLogByID(ctx context.Context, id string) (*models.EmailLog, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindEmailLogByID")
	}

	var r0 *models.EmailLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.EmailLog, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.EmailLog); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EmailLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindEmailLogs provides a mock function with given fields: ctx, filter, page, limit
func (_m *Repository) FindEmailLogs(ctx context.Context, filter interface{}, page int, limit int) ([]*models.EmailLog, int64, error) {
	ret := _m.Called(ctx, filter, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindEmailLogs")
	}

	var r0 []*models.EmailLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, int, int) ([]*models.EmailLog, int64, error)); ok {
		return rf(ctx, filter, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, int, int) []*models.EmailLog); ok {
		r0 = rf(ctx, filter, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.EmailLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, int, int) int64); ok {
		r1 = rf(ctx, filter, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, interface{}, int, int) error); ok {
		r2 = rf(ctx, filter, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindEmails provides a mock function with given fields: ctx, filter, page, limit
func (_m *Repository) FindEmails(ctx context.Context, filter interface{}, page int, limit int) ([]*models.Email, int64, error) {
	ret := _m.Called(ctx, filter, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindEmails")
	}

	var r0 []*models.Email
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, int, int) ([]*models.Email, int64, error)); ok {
		return rf(ctx, filter, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, int, int) []*models.Email); ok {
		r0 = rf(ctx, filter, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Email)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, int, int) int64); ok {
		r1 = rf(ctx, filter, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, interface{}, int, int) error); ok {
		r2 = rf(ctx, filter, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindUserByEmail provides a mock function with given fields: ctx, email
func (_m *Repository) FindUserByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByID provides a mock function with given fields: ctx, id
func (_m *Repository) FindUserByID(ctx context.Context, id string) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUsers provides a mock function with given fields: ctx, filter, page, limit
func (_m *Repository) FindUsers(ctx context.Context, filter interface{}, page int, limit int) ([]*models.User, int64, error) {
	ret := _m.Called(ctx, filter, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindUsers")
	}

	var r0 []*models.User
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, int, int) ([]*models.User, int64, error)); ok {
		return rf(ctx, filter, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, int, int) []*models.User); ok {
		r0 = rf(ctx, filter, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, int, int) int64); ok {
		r1 = rf(ctx, filter, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, interface{}, int, int) error); ok {
		r2 = rf(ctx, filter, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// InitTokenIndexes provides a mock function with given fields: ctx
func (_m *Repository) InitTokenIndexes(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitTokenIndexes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsTokenRevoked provides a mock function with given fields: ctx, tokenID
func (_m *Repository) IsTokenRevoked(ctx context.Context, tokenID string) (bool, error) {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenRevoked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, tokenID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeToken provides a mock function with given fields: ctx, token
func (_m *Repository) RevokeToken(ctx context.Context, token *models.RevokedToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.RevokedToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveEmail provides a mock function with given fields: ctx, email
func (_m *Repository) SaveEmail(ctx context.Context, email *models.Email) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for SaveEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Email) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveEmailLog provides a mock function with given fields: ctx, emailLog
func (_m *Repository) SaveEmailLog(ctx context.Context, emailLog *models.EmailLog) error {
	ret := _m.Called(ctx, emailLog)

	if len(ret) == 0 {
		panic("no return value specified for SaveEmailLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.EmailLog) error); ok {
		r0 = rf(ctx, emailLog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveUser provides a mock function with given fields: ctx, user
func (_m *Repository) SaveUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
