env: "dev"

server:
  port: "8080"
  portGRPC: "50051"
  readTimeout: 10s
  writeTimeout: 10s


mongodb:
  uri: "mongodb://localhost:27017/"
  username: "username"
  password: "123"
  database: "gomail"
  endpoint: "localhost:27017"
  timeout: 10s
  connectionTimeout: 10s

smtp:
  host: "smtp.example.net"
  port: "587"
  username: "apikey"
  password: "password"
  from: "noreply@nandhu.wiki"
  tlsEnable: true

jwt:
  secret: "your_jwt_secret_key_change_in_production"
  expiresIn: 24h

cors:
  allowedOrigins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  allowedMethods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowedHeaders:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  exposeHeaders:
    - "Content-Length"
  maxAge: 86400

services:
  auth:
    url: "http://localhost"
    port: "8081"
  notification:
    url: "http://localhost"
    port: "8082"

logLevel: "info" 